name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Detect version bump level from commit message
        id: detect
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo "Commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"[major]"* ]]; then
            echo "level=major" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[minor]"* ]]; then
            echo "level=minor" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MSG" == *"[patch]"* ]]; then
            echo "level=patch" >> $GITHUB_OUTPUT
          else
            echo "No bump keyword found. Skipping."
            exit 0
          fi

      - name: Get package name from pyproject.toml
        id: package
        if: ${{ steps.detect.outputs.level != '' }}
        run: |
          NAME=$(python bump_version.py --print-package)
          echo "PACKAGE_NAME=$NAME" >> $GITHUB_OUTPUT

      - name: Bump version
        if: ${{ steps.detect.outputs.level != '' }}
        run: |
          python bump_version.py ${{ steps.detect.outputs.level }}

      - name: Get new version
        id: version
        if: ${{ steps.detect.outputs.level != '' }}
        run: |
          VERSION=$(python bump_version.py --print-version)
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        if: ${{ steps.detect.outputs.level != '' }}
        run: |
          echo "Detected package folder: ${{ steps.package.outputs.PACKAGE_NAME }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml "${{ steps.package.outputs.PACKAGE_NAME }}/__init__.py"
          git commit -m "🔖 Bump version [${{ steps.detect.outputs.level }}]" || echo "No changes to commit"
          git push

      - name: Create git tag
        if: ${{ steps.detect.outputs.level != '' }}
        run: |
          git tag "v${{ steps.version.outputs.new_version }}"
          git push origin "v${{ steps.version.outputs.new_version }}"
